// The teaching-room equipment and software list.
//
// GENERATED by `scripts/build-rooms-data.py` from
// `ref/Summer Helpers 2026 - Room Equipment List.csv`, the Summer Helpers 2026
// room-checking result. Do not edit by hand: change the CSV, re-run the script,
// and diff the result.
//
// Room codes are kept exactly as the sheet — and the door signs — write them,
// in every locale. Everything around them is a translation key: room types are
// `rooms.type.*`, column names `rooms.attr.*`, and the qualifiers the sheet
// writes inside a cell ("On-loan request", "Facing Teacher", `86" Interactive
// Panel") are `rooms.note.*`, so a Chinese page does not fall back to English
// halfway down a card.
//
// `RoomEquipment.vue` is the only reader.

export const BUILDINGS = [
  'AUD',
  'LBY',
  'LCH',
  'LKK',
  'LYH',
  'MB',
  'SEK',
  'WYL',
] as const

export type Building = (typeof BUILDINGS)[number]

/**
 * Room types, in the order the sheet first uses them. The sheet is not
 * consistent about the four computer-lab names — `Computer Lab`,
 * `Computer Laboratory`, `Computer Teaching Lab` and
 * `Teaching Computer Laboratory` all appear — and they are kept apart here
 * rather than merged, because merging would put words in the sheet's mouth.
 */
export const ROOM_TYPES = [
  'multiPurposeHall', // Multi-purpose Hall
  'languageLaboratory', // Language Laboratory
  'lectureTheatre', // Lecture Theatre
  'lectureRoom', // Lecture Room
  'scienceLaboratory', // Science Laboratory
  'computerTeachingLab', // Computer Teaching Lab
  'teachingComputerLaboratory', // Teaching Computer Laboratory
  'computerLab', // Computer Lab
  'musicLabLaboratory', // Music Lab Laboratory
  'aiLaboratory', // AI Laboratory
  'tutorialRoom', // Tutorial Room
  'conferencingRoom', // Conferencing Room
  'functionRoom', // Function Room
  'cdsTeachingLaboratory', // CDS Teaching Laboratory
  'computerLaboratory', // Computer Laboratory
  'meetingRoom', // Meeting Room
] as const

export type RoomType = (typeof ROOM_TYPES)[number]

/** Every column, in the eight groups the detail panel renders. */
export const ATTRIBUTE_GROUPS = {
  teachingStation: ['pcDual', 'notebook'],
  display: ['projector', 'displayPanel', 'visualizer'],
  camera: ['webcam', 'ptz'],
  opticalDrive: ['usbBluray', 'cdRom'],
  network: ['wirelessGateway'],
  mic: ['gooseneckMic', 'irWirelessMic', 'digitalWirelessMic', 'wiredMic', 'ceilingMic'],
  printer: ['printer'],
  software: ['xclass', 'spssAmos', 'sdl', 'matlab'],
} as const

export type AttributeGroup = keyof typeof ATTRIBUTE_GROUPS
export type Attribute = (typeof ATTRIBUTE_GROUPS)[AttributeGroup][number]

/**
 * One entry in a sheet cell.
 *
 * The sheet counts some things and ticks others: `3 (On-loan request)` becomes
 * `{ count: 3, note: 'onLoanRequest' }`, a bare `Yes` becomes
 * `{ count: null, note: null }`, and `Single monitor` becomes
 * `{ count: null, note: 'singleMonitor' }`. A cell holding two lines — a webcam
 * facing the teacher and one facing the students — becomes two entries.
 */
export interface Spec {
  /** How many, when the sheet gives a number. */
  count: number | null
  /** Key into `rooms.note.*`, when the sheet qualifies the entry. */
  note: string | null
}

export interface Room {
  /** Slug of the room code, and the anchor other pages deep-link to. */
  id: string
  building: Building
  /** Room code, as the rota and the door sign write it. */
  code: string
  /** The hall's name, for the three rooms the sheet names; null otherwise. */
  name: string | null
  type: RoomType
  /**
   * Only the columns the sheet fills in. A missing key means the cell is
   * blank — which is not the same as a confirmed "no", and the page says so.
   */
  equipment: Partial<Record<Attribute, Spec[]>>
}

export const ROOMS: Room[] = [
  {
    id: 'aud',
    building: 'AUD',
    code: 'AUD',
    name: 'Chan Tak Tai Auditorium',
    type: 'multiPurposeHall',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: 'ocdm' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lby301',
    building: 'LBY',
    code: 'LBY301',
    name: null,
    type: 'languageLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      printer: [{ count: 1, note: 'bw' }],
      xclass: [{ count: null, note: null }],
      sdl: [{ count: null, note: null }]
    }
  },
  {
    id: 'lby303',
    building: 'LBY',
    code: 'LBY303',
    name: null,
    type: 'languageLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      printer: [{ count: 1, note: 'bw' }],
      xclass: [{ count: null, note: null }],
      sdl: [{ count: null, note: null }]
    }
  },
  {
    id: 'lbyg01',
    building: 'LBY',
    code: 'LBYG01',
    name: null,
    type: 'lectureTheatre',
    equipment: {
      notebook: [{ count: null, note: null }],
      visualizer: [{ count: 1, note: null }],
      ptz: [{ count: 3, note: null }],
      usbBluray: [{ count: 1, note: null }],
      wirelessGateway: [{ count: 14, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [
        { count: 1, note: 'rechargeableOnLectern' },
        { count: 2, note: 'onLoanRequest' },
      ],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lbyg02',
    building: 'LBY',
    code: 'LBYG02',
    name: null,
    type: 'lectureTheatre',
    equipment: {
      notebook: [{ count: null, note: null }],
      visualizer: [{ count: 1, note: null }],
      ptz: [{ count: 3, note: null }],
      usbBluray: [{ count: 1, note: null }],
      wirelessGateway: [{ count: 19, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [
        { count: 1, note: 'rechargeableOnLectern' },
        { count: 2, note: 'onLoanRequest' },
      ],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lbyg06',
    building: 'LBY',
    code: 'LBYG06',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'ledWall108' }, { count: 1, note: 'confidentMonitor43' }],
      visualizer: [{ count: 1, note: null }],
      ptz: [{ count: 2, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      digitalWirelessMic: [{ count: 2, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch101',
    building: 'LCH',
    code: 'LCH101',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch102',
    building: 'LCH',
    code: 'LCH102',
    name: null,
    type: 'lectureRoom',
    equipment: {
      webcam: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch103',
    building: 'LCH',
    code: 'LCH103',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch104',
    building: 'LCH',
    code: 'LCH104',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch105',
    building: 'LCH',
    code: 'LCH105',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch106',
    building: 'LCH',
    code: 'LCH106',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch110',
    building: 'LCH',
    code: 'LCH110',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch111',
    building: 'LCH',
    code: 'LCH111',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch113',
    building: 'LCH',
    code: 'LCH113',
    name: null,
    type: 'scienceLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 2, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch115',
    building: 'LCH',
    code: 'LCH115',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch117',
    building: 'LCH',
    code: 'LCH117',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch118',
    building: 'LCH',
    code: 'LCH118',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch201',
    building: 'LCH',
    code: 'LCH201',
    name: null,
    type: 'languageLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      cdRom: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      printer: [{ count: 1, note: 'bw' }],
      xclass: [{ count: null, note: null }],
      sdl: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch201a',
    building: 'LCH',
    code: 'LCH201A',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }],
      cdRom: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: 'r2024b' }]
    }
  },
  {
    id: 'lch202',
    building: 'LCH',
    code: 'LCH202',
    name: null,
    type: 'languageLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      cdRom: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      printer: [{ count: 1, note: 'bw' }],
      xclass: [{ count: null, note: null }],
      sdl: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch204',
    building: 'LCH',
    code: 'LCH204',
    name: null,
    type: 'computerTeachingLab',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }],
      usbBluray: [{ count: 1, note: null }],
      cdRom: [{ count: null, note: 'all' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: null, note: null }],
      wiredMic: [{ count: 1, note: null }],
      printer: [{ count: 1, note: 'bw' }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: 'r2024b' }]
    }
  },
  {
    id: 'lch206',
    building: 'LCH',
    code: 'LCH206',
    name: null,
    type: 'teachingComputerLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      usbBluray: [{ count: 1, note: null }],
      cdRom: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: null, note: null }],
      wiredMic: [{ count: 1, note: null }],
      printer: [{ count: 1, note: 'bw' }],
      xclass: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }],
      sdl: [{ count: null, note: null }],
      matlab: [{ count: null, note: 'r2026a' }]
    }
  },
  {
    id: 'lch206a',
    building: 'LCH',
    code: 'LCH206A',
    name: null,
    type: 'computerLab',
    equipment: {
      printer: [{ count: 1, note: 'bw' }, { count: 1, note: 'colour' }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch209',
    building: 'LCH',
    code: 'LCH209',
    name: null,
    type: 'teachingComputerLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      printer: [{ count: 1, note: 'bw' }],
      xclass: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch213',
    building: 'LCH',
    code: 'LCH213',
    name: null,
    type: 'teachingComputerLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      usbBluray: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      printer: [{ count: 1, note: 'bw' }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: 'r2026a' }]
    }
  },
  {
    id: 'lch214',
    building: 'LCH',
    code: 'LCH214',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch319ab',
    building: 'LCH',
    code: 'LCH319AB',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 2, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch319cd',
    building: 'LCH',
    code: 'LCH319CD',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 2, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 2, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch411',
    building: 'LCH',
    code: 'LCH411',
    name: null,
    type: 'musicLabLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      wirelessGateway: [{ count: null, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [{ count: 2, note: null }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch413',
    building: 'LCH',
    code: 'LCH413',
    name: null,
    type: 'aiLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 4, note: 'videoWall2x2' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      wirelessGateway: [{ count: null, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [{ count: 2, note: 'rechargeableOnLectern' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch414-2',
    building: 'LCH',
    code: 'LCH414/2',
    name: null,
    type: 'scienceLaboratory',
    equipment: {
      pcDual: [{ count: null, note: 'singleMonitor' }],
      displayPanel: [{ count: 1, note: 'touchPanel' }],
      visualizer: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 2, note: null }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lch416',
    building: 'LCH',
    code: 'LCH416',
    name: null,
    type: 'scienceLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'touchPanel' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 1, note: null }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lchlg01',
    building: 'LCH',
    code: 'LCHLG01',
    name: 'Sin Chow Ming Hall',
    type: 'multiPurposeHall',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 2, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [
        { count: 1, note: 'rechargeableOnLectern' },
        { count: 2, note: 'onLoanRequest' },
      ],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lchug04b',
    building: 'LCH',
    code: 'LCHUG04B',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lchug08',
    building: 'LCH',
    code: 'LCHUG08',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lchug09',
    building: 'LCH',
    code: 'LCHUG09',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lchug10',
    building: 'LCH',
    code: 'LCHUG10',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lchug11',
    building: 'LCH',
    code: 'LCHUG11',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lchug12',
    building: 'LCH',
    code: 'LCHUG12',
    name: null,
    type: 'lectureRoom',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lchug14',
    building: 'LCH',
    code: 'LCHUG14',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk101',
    building: 'LKK',
    code: 'LKK101',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk102',
    building: 'LKK',
    code: 'LKK102',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk103',
    building: 'LKK',
    code: 'LKK103',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk104',
    building: 'LKK',
    code: 'LKK104',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk105',
    building: 'LKK',
    code: 'LKK105',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk106',
    building: 'LKK',
    code: 'LKK106',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk107',
    building: 'LKK',
    code: 'LKK107',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk108',
    building: 'LKK',
    code: 'LKK108',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk110',
    building: 'LKK',
    code: 'LKK110',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk201',
    building: 'LKK',
    code: 'LKK201',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk202',
    building: 'LKK',
    code: 'LKK202',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk203',
    building: 'LKK',
    code: 'LKK203',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk204',
    building: 'LKK',
    code: 'LKK204',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk205',
    building: 'LKK',
    code: 'LKK205',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk206',
    building: 'LKK',
    code: 'LKK206',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk207',
    building: 'LKK',
    code: 'LKK207',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk208',
    building: 'LKK',
    code: 'LKK208',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk210',
    building: 'LKK',
    code: 'LKK210',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk301',
    building: 'LKK',
    code: 'LKK301',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk302',
    building: 'LKK',
    code: 'LKK302',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk303',
    building: 'LKK',
    code: 'LKK303',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk304',
    building: 'LKK',
    code: 'LKK304',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk305',
    building: 'LKK',
    code: 'LKK305',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk306',
    building: 'LKK',
    code: 'LKK306',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk307',
    building: 'LKK',
    code: 'LKK307',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk308',
    building: 'LKK',
    code: 'LKK308',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkk310',
    building: 'LKK',
    code: 'LKK310',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkkg01',
    building: 'LKK',
    code: 'LKKG01',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      displayPanel: [{ count: 4, note: null }],
      visualizer: [{ count: 1, note: null }],
      ptz: [{ count: 2, note: null }],
      wirelessGateway: [{ count: 5, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkkg02',
    building: 'LKK',
    code: 'LKKG02',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      displayPanel: [{ count: 4, note: null }],
      visualizer: [{ count: 1, note: null }],
      ptz: [{ count: 2, note: null }],
      wirelessGateway: [{ count: 5, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkkg03',
    building: 'LKK',
    code: 'LKKG03',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      displayPanel: [{ count: 4, note: null }],
      visualizer: [{ count: 1, note: null }],
      ptz: [{ count: 2, note: null }],
      wirelessGateway: [{ count: 5, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkkg04',
    building: 'LKK',
    code: 'LKKG04',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      displayPanel: [{ count: 4, note: null }],
      visualizer: [{ count: 1, note: null }],
      ptz: [{ count: 2, note: null }],
      wirelessGateway: [{ count: 5, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lkkg05',
    building: 'LKK',
    code: 'LKKG05',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      displayPanel: [{ count: 5, note: null }],
      visualizer: [{ count: 1, note: null }],
      ptz: [{ count: 2, note: null }],
      wirelessGateway: [{ count: 6, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lyh111',
    building: 'LYH',
    code: 'LYH111',
    name: null,
    type: 'lectureRoom',
    equipment: {
      notebook: [{ count: null, note: null }],
      displayPanel: [{ count: 4, note: 'videoWall2x2' }],
      visualizer: [{ count: 1, note: null }],
      ptz: [{ count: 2, note: null }],
      usbBluray: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      digitalWirelessMic: [{ count: 1, note: 'rechargeableOnLectern' }],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: null }]
    }
  },
  {
    id: 'lyh112',
    building: 'LYH',
    code: 'LYH112',
    name: null,
    type: 'lectureRoom',
    equipment: {
      notebook: [{ count: null, note: null }],
      displayPanel: [{ count: 4, note: 'videoWall2x2' }],
      visualizer: [{ count: 1, note: null }],
      ptz: [{ count: 2, note: null }],
      usbBluray: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      digitalWirelessMic: [{ count: 1, note: 'rechargeableOnLectern' }],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: 'r2024a' }]
    }
  },
  {
    id: 'lyh201-1',
    building: 'LYH',
    code: 'LYH201/1',
    name: null,
    type: 'lectureRoom',
    equipment: {
      notebook: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      ptz: [{ count: 2, note: null }],
      usbBluray: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: 'r2024a' }]
    }
  },
  {
    id: 'lyh201-2',
    building: 'LYH',
    code: 'LYH201/2',
    name: null,
    type: 'lectureRoom',
    equipment: {
      notebook: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      displayPanel: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      ptz: [{ count: 2, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: 'r2024a' }]
    }
  },
  {
    id: 'lyh308',
    building: 'LYH',
    code: 'LYH308',
    name: null,
    type: 'conferencingRoom',
    equipment: {
      projector: [{ count: 2, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }, { count: 4, note: 'display65' }],
      usbBluray: [{ count: 2, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lyh309',
    building: 'LYH',
    code: 'LYH309',
    name: null,
    type: 'conferencingRoom',
    equipment: {
      notebook: [{ count: null, note: 'noMonitor' }],
      projector: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: null }],
      digitalWirelessMic: [{ count: 2, note: 'onLoanRequest' }],
      wiredMic: [{ count: 2, note: 'handheldMic' }, { count: null, note: 'dectMic' }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lyh310',
    building: 'LYH',
    code: 'LYH310',
    name: null,
    type: 'conferencingRoom',
    equipment: {
      notebook: [{ count: null, note: 'noMonitor' }],
      displayPanel: [{ count: 3, note: 'display85' }],
      usbBluray: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [{ count: 2, note: 'onLoanRequest' }],
      wiredMic: [{ count: 2, note: 'handheldMic' }, { count: null, note: 'dectMic' }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lyh316',
    building: 'LYH',
    code: 'LYH316',
    name: null,
    type: 'functionRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      cdRom: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 2, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: 'r2026a' }]
    }
  },
  {
    id: 'lyh317',
    building: 'LYH',
    code: 'LYH317',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'ledWall108' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [{ count: 1, note: 'rechargeableOnLectern' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'lyh319',
    building: 'LYH',
    code: 'LYH319',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 2, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      cdRom: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [{ count: 1, note: 'rechargeableOnLectern' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: 'r2024b' }]
    }
  },
  {
    id: 'lyh320',
    building: 'LYH',
    code: 'LYH320',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'ledWall108' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      cdRom: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [{ count: 1, note: 'rechargeableOnLectern' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: 'r2024b' }]
    }
  },
  {
    id: 'mb202',
    building: 'MB',
    code: 'MB202',
    name: null,
    type: 'teachingComputerLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      cdRom: [{ count: 1, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      printer: [{ count: 1, note: 'bw' }],
      xclass: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: 'r2024b' }]
    }
  },
  {
    id: 'mbg01',
    building: 'MB',
    code: 'MBG01',
    name: null,
    type: 'lectureTheatre',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      usbBluray: [{ count: 1, note: null }],
      wirelessGateway: [{ count: null, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [
        { count: 1, note: 'rechargeableOnLectern' },
        { count: 2, note: 'onLoanRequest' },
      ],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'mbg06',
    building: 'MB',
    code: 'MBG06',
    name: null,
    type: 'lectureTheatre',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      wirelessGateway: [{ count: null, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [
        { count: 1, note: 'rechargeableOnLectern' },
        { count: 2, note: 'onLoanRequest' },
      ],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'mbg07',
    building: 'MB',
    code: 'MBG07',
    name: null,
    type: 'lectureTheatre',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      displayPanel: [{ count: 4, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingStudent' }],
      ptz: [{ count: 3, note: null }],
      usbBluray: [{ count: 1, note: null }],
      wirelessGateway: [{ count: 5, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [
        { count: 1, note: 'rechargeableOnLectern' },
        { count: 2, note: 'onLoanRequest' },
      ],
      wiredMic: [{ count: 1, note: null }],
      ceilingMic: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'mbg09',
    building: 'MB',
    code: 'MBG09',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'mbg10',
    building: 'MB',
    code: 'MBG10',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'mbg11',
    building: 'MB',
    code: 'MBG11',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'mbg12',
    building: 'MB',
    code: 'MBG12',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'mbg19',
    building: 'MB',
    code: 'MBG19',
    name: null,
    type: 'lectureTheatre',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      usbBluray: [{ count: 1, note: null }],
      wirelessGateway: [{ count: null, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [
        { count: 1, note: 'rechargeableOnLectern' },
        { count: 2, note: 'onLoanRequest' },
      ],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'mbg22',
    building: 'MB',
    code: 'MBG22',
    name: null,
    type: 'lectureTheatre',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      usbBluray: [{ count: 1, note: null }],
      wirelessGateway: [{ count: null, note: null }],
      gooseneckMic: [{ count: 1, note: null }],
      digitalWirelessMic: [
        { count: 1, note: 'rechargeableOnLectern' },
        { count: 2, note: 'onLoanRequest' },
      ],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'sek104',
    building: 'SEK',
    code: 'SEK104',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 2, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'sek105',
    building: 'SEK',
    code: 'SEK105',
    name: null,
    type: 'cdsTeachingLaboratory',
    equipment: {
      pcDual: [{ count: null, note: 'singleMonitor' }, { count: null, note: 'allInOnePc' }],
      displayPanel: [
        { count: 2, note: 'display85Corridor' },
        { count: 4, note: 'display85Discussion' },
        { count: 4, note: 'touchScreen42Discussion' },
        { count: 4, note: 'display85Classroom' },
      ],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'allInOnePc' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: null, note: null }],
      wiredMic: [{ count: 1, note: null }],
      xclass: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: 'r2026a' }]
    }
  },
  {
    id: 'sek106',
    building: 'SEK',
    code: 'SEK106',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'sek107',
    building: 'SEK',
    code: 'SEK107',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'sek108',
    building: 'SEK',
    code: 'SEK108',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'sek205',
    building: 'SEK',
    code: 'SEK205',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 2, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'sek206',
    building: 'SEK',
    code: 'SEK206',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 2, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'sekg02',
    building: 'SEK',
    code: 'SEKG02',
    name: null,
    type: 'teachingComputerLaboratory',
    equipment: {
      pcDual: [{ count: null, note: 'singleMonitor' }],
      projector: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      printer: [{ count: 2, note: 'bw' }, { count: 1, note: 'colour' }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'sekg02-1',
    building: 'SEK',
    code: 'SEKG02/1',
    name: null,
    type: 'computerLaboratory',
    equipment: {
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'sekg03',
    building: 'SEK',
    code: 'SEKG03',
    name: null,
    type: 'teachingComputerLaboratory',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'ledWall163' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      printer: [{ count: 1, note: 'bw' }],
      xclass: [{ count: null, note: null }],
      spssAmos: [{ count: null, note: null }],
      matlab: [{ count: null, note: null }]
    }
  },
  {
    id: 'sekg09',
    building: 'SEK',
    code: 'SEKG09',
    name: 'Chan Wai Nam Function Hall',
    type: 'multiPurposeHall',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 2, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 2, note: 'onLoanRequest' }],
      digitalWirelessMic: [{ count: 2, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'wyl101',
    building: 'WYL',
    code: 'WYL101',
    name: null,
    type: 'lectureRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      projector: [{ count: 1, note: null }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'wyl103',
    building: 'WYL',
    code: 'WYL103',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel75' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'wyl105',
    building: 'WYL',
    code: 'WYL105',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel75' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'wyl107',
    building: 'WYL',
    code: 'WYL107',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel75' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'wyl109',
    building: 'WYL',
    code: 'WYL109',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel75' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'wyl111',
    building: 'WYL',
    code: 'WYL111',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'wyl113',
    building: 'WYL',
    code: 'WYL113',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel86' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'wyl115',
    building: 'WYL',
    code: 'WYL115',
    name: null,
    type: 'tutorialRoom',
    equipment: {
      pcDual: [{ count: null, note: null }],
      displayPanel: [{ count: 1, note: 'interactivePanel75' }],
      visualizer: [{ count: 1, note: null }],
      webcam: [{ count: 1, note: 'facingTeacher' }, { count: 1, note: 'facingStudent' }],
      gooseneckMic: [{ count: 1, note: null }],
      irWirelessMic: [{ count: 3, note: 'onLoanRequest' }],
      wiredMic: [{ count: 1, note: null }],
      spssAmos: [{ count: null, note: null }]
    }
  },
  {
    id: 'wyl314',
    building: 'WYL',
    code: 'WYL314',
    name: null,
    type: 'meetingRoom',
    equipment: {
      pcDual: [{ count: null, note: 'noMonitor' }],
      displayPanel: [{ count: 1, note: 'display98' }],
      usbBluray: [{ count: 2, note: null }],
      digitalWirelessMic: [{ count: 2, note: 'onLoanRequest' }],
      spssAmos: [{ count: null, note: null }]
    }
  }
]
